# strategy_params.py

from symbols_config import SYMBOLS

default_settings = {"timeframe": "4h", "cycle_interval": 3000}
BOT_SETTINGS = {symbol: default_settings.copy() for symbol in SYMBOLS}

USE_TESTNET = True
API_KEY = "GqM3BCiJ5O0QezhQpI52hEP1SiT3dZg6Rwt9X5pT32qOn5Vvvo7wfRxxU0EYqq02"
API_SECRET = "fJRjqVD1CoSQj3uakUQyKyh8qOKK4NDWQcgoVWagKmCdJtRtXRrqd1qI4gGH32DJ"

CHIUDI_ORDINE = "OBV"
EMA_CHIUSURA_ORDINE = "Media mobile 1"
LC_PERCENT_LOSS = 3.3
GRAFICO = "OBV"

MA_TYPE_INPUT = "SMA + Bollinger Bands"
MA_LENGTH_INPUT = 26
BB_MULT_INPUT = 2

LC_TIPO_MA = "WMA"
LC_MA1_NPERIODI = 5
LC_MA2_NPERIODI = 10
LC_MA3_NPERIODI = 60
LC_MA4_NPERIODI = 223

LC_RSI_NPERIODI = 6
LC_RSI_MA_NPERIODI = 9
RSI_LIMITE_SUPERIORE = 80
RSI_LIMITE_INFERIORE = 20
RSI_CENTRO_LIMITI = (RSI_LIMITE_SUPERIORE + RSI_LIMITE_INFERIORE) / 2

FAST_LENGTH = 12
SLOW_LENGTH = 26
SIGNAL_LENGTH = 18

INTERVAL = "4h"
LOOKBACK_DAYS = 300
